version: '3.8'

services:
  postgres:
    image: postgres:15.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:6.2.6-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: --port 5555
    ports:
      - "5555:5555"

  backend:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:7000
    ports:
      - "7000:7000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_NODENAME: "rabbit@localhost"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
    volumes:
      - rabbit_data:/data

  celery:
    build: ./backend
    restart: always
    command: bash -c "celery -A backend worker -l INFO"
    volumes:
      - static_value:/app/static/
    depends_on:
      - rabbit
    env_file:
      - .env

volumes:
  rabbit_data:
  postgres_data:
  redis_data:
  static_value:
  media_value: